Dark theme
pikaviestin/website-www.pikaviestin.fi pull request #5
Opened 2021-12-03 22:20 UTC by samip5

Mitäs ootte mieltä?

2021-12-03 22:29 UTC, uumas commented
Favicon näyttää vähän out of place tässä ku se on valkotaustanen. Joka tapauksessa mun mielestä tän pitäis olla vaihtoehto, ei default.

2021-12-19 10:56 UTC, samip5 commented
Oiskos tähän mahdollista saada muiden kommentteja?

2021-12-19 11:40 UTC, vranki commented
Lähdetääs nyt ensin siitä että mitä tämä PR tekee? Johonkin dark themeen liittyvä muutos kyseessä, mutta kerrotko vähän tarkemmin mistä kyse.

2021-12-19 11:40 UTC, samip5 commented
Käytännössä siis vaihtaa oletus väriteeman tummaksi.

2021-12-19 11:46 UTC, vranki commented
Kyseessä on tekstipohjainen mahdollisimman ystävälliseksi haluttu sivusto joten vaalea tausta on mielestäni parempi vaihtoehto. 

Vaikka tummia teemoja käytänkin itse, niin vaaleat näyttävät "ystävällisemmiltä". Koitin tähän etsiä jotain faktaa tän perusteeksi ja esim https://design4users.com/ui-design-light-and-dark-theme/ sanoo "If the UI is text-driven (a blog, news platform, e-reader, etc.), light background tends to be an effective choice. Light makes the screen airy and spacious and it will be easier to concentrate purely on the copy. "

2021-12-19 11:48 UTC, samip5 commented
En oo kyllä yhtään samaa mieltä. Yritä katsoa tota sivua yöllä pimeässä huoneessa, silmät "tykkää".

2024-07-04 05:29 UTC, Mikaela requested changes
Eikö tämä pitäisi toteuttaa `color-scheme: light dark` ja media queryillä `(prefers-color-scheme: dark)`?

2024-07-04 07:58 UTC, closed without merging